apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: metal-investment
  name: metal-investment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metal-investment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: metal-investment
    spec:
      containers:
      - image: nelucristian/metal-investment
        name: metal-investment
        resources: {}
        env:
        - name: METAL_INVESTMENT_MAIL_FROM
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: METAL_INVESTMENT_MAIL_FROM
        - name: METAL_INVESTMENT_MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: METAL_INVESTMENT_MAIL_PASSWORD
        - name: METAL_INVESTMENT_MAIL_PORT
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: METAL_INVESTMENT_MAIL_PORT
        - name: METAL_INVESTMENT_MAIL_HOST
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: METAL_INVESTMENT_MAIL_HOST
        - name: METAL_INVESTMENT_ENCODER_SECRETE
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: METAL_INVESTMENT_ENCODER_SECRETE

      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_ROOT_HOST
          value: "%"
        - name: MYSQL_DATABASE
          value: "metals"
        ports:
        - containerPort: 3306
          name: mysql
status: {}
--- 
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: metal-investment
  name: metal-investment
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: metal-investment
  clusterIP: 10.96.1.1
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 192.0.2.127
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  MYSQL_USER: *************
  MYSQL_PASSWORD: ************
  MYSQL_ROOT_PASSWORD: ************
  METAL_INVESTMENT_MAIL_FROM: ************
  METAL_INVESTMENT_MAIL_PASSWORD: ************
  METAL_INVESTMENT_MAIL_PORT: ************
  METAL_INVESTMENT_MAIL_HOST: ************
  METAL_INVESTMENT_ENCODER_SECRETE: ************