#The only difference between docker-compose.yaml and this debug file is moving
#from Dockerfile "ENTRYPOINT"  into "command" of the compose file
#don't forget in compose run config set=true "--build/force build images"

#create a network and add our services into this network:
#so, "app" service will be able to connect to the mysql database from "db" servoce by the hostname="db":
#jdbc:mysql://db:3306/DOCKERDB

#Connection url for connection in the DatabaseView:
#  jdbc:mysql://0.0.0.0:13306/DOCKERDB, login=root, password=root
#App is available at: http://localhost:18080/entitybus/post
version: "3.8"

networks:
  test:

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18080:8080"
    networks:
      - test
    command: java -jar /target/metal-investment-0.0.1.jar


  docker-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: metals
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: Nelu1810728
    ports:
      - '3307:3306'
    healthcheck:
      test: [ "CMD", "mysql", "-h", "localhost", "-P", "3306", "-u", "test", "--password=test", "-e", "select 1", "metals" ]
      interval: 1s
      timeout: 3s
      retries: 30
    expose:
      # Opens port 3306 on the container
      - '3306'
    networks:
      - test
